# Generated by Django 3.1.7 on 2021-02-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('frame', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'collector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_id', models.IntegerField(null=True, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('detector_identifier', models.CharField(max_length=16)),
                ('uptime_days', models.IntegerField()),
                ('uptime_hours', models.IntegerField()),
                ('uptime_minutes', models.IntegerField()),
                ('uptime_seconds', models.IntegerField()),
                ('sensor_1', models.IntegerField()),
                ('sensor_2', models.IntegerField()),
                ('sensor_3', models.IntegerField()),
                ('sensor_4', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area_type', models.CharField(choices=[('House', 0), ('Location', 1), ('Village', 2), ('Town', 3), ('City', 4), ('State', 5), ('Region', 6), ('Country', 7)], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('detector_type', models.CharField(choices=[('KissingBug', 0)], max_length=16)),
                ('identifier', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddIndex(
            model_name='detector',
            index=models.Index(fields=['identifier'], name='core_detect_identif_befec2_idx'),
        ),
        migrations.AddIndex(
            model_name='detector',
            index=models.Index(fields=['detector_type'], name='core_detect_detecto_f3e21a_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['name'], name='core_area_name_ec8dff_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['area_type'], name='core_area_area_ty_f1289c_idx'),
        ),
        migrations.AddIndex(
            model_name='activation',
            index=models.Index(fields=['detector_identifier'], name='core_activa_detecto_85cb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='activation',
            index=models.Index(fields=['count'], name='core_activa_count_cc89df_idx'),
        ),
        migrations.AddIndex(
            model_name='activation',
            index=models.Index(fields=['timestamp'], name='core_activa_timesta_af9363_idx'),
        ),
    ]
