# Generated by Django 3.1.7 on 2021-03-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('House', 'House'), ('Location', 'Location'), ('Village', 'Village'), ('Town', 'Town'), ('City', 'City'), ('State', 'State'), ('Region', 'Region'), ('Country', 'Country')], max_length=16),
        ),
        migrations.AlterField(
            model_name='detector',
            name='detector_type',
            field=models.CharField(choices=[('KissingBug', 'KissingBug')], max_length=16),
        ),
    ]
