# Generated by Django 3.1.7 on 2021-02-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('detector_identifier', models.CharField(max_length=16)),
                ('uptime_days', models.IntegerField()),
                ('uptime_hours', models.IntegerField()),
                ('uptime_minutes', models.IntegerField()),
                ('uptime_seconds', models.IntegerField()),
                ('sensor_1', models.IntegerField()),
                ('sensor_2', models.IntegerField()),
                ('sensor_3', models.IntegerField()),
                ('sensor_4', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area_type', models.CharField(choices=[('House', 0), ('Location', 1), ('Village', 2), ('Town', 3), ('City', 4), ('State', 5), ('Region', 6), ('Country', 7)], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('detector_type', models.CharField(choices=[('KissingBug', 0)], max_length=16)),
                ('identifier', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddIndex(
            model_name='detector',
            index=models.Index(fields=['identifier'], name='dashboard_d_identif_ae415d_idx'),
        ),
        migrations.AddIndex(
            model_name='detector',
            index=models.Index(fields=['detector_type'], name='dashboard_d_detecto_2c5643_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['name'], name='dashboard_a_name_240c38_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['area_type'], name='dashboard_a_area_ty_4a7145_idx'),
        ),
        migrations.AddIndex(
            model_name='activation',
            index=models.Index(fields=['detector_identifier'], name='dashboard_a_detecto_b33656_idx'),
        ),
        migrations.AddIndex(
            model_name='activation',
            index=models.Index(fields=['count'], name='dashboard_a_count_1b8e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='activation',
            index=models.Index(fields=['timestamp'], name='dashboard_a_timesta_dc2dc8_idx'),
        ),
    ]
