# Generated by Django 3.1.7 on 2021-02-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('frame', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'collector',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='activation',
            name='collector_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
